
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import load_model
from tensorflow.keras.preprocessing import image


class birds:
    def __init__(self, filename):
        self.filename = filename
    birds_list = ['AFRICAN FIREFINCH',
                  'ALBATROSS',
                  'ALEXANDRINE PARAKEET',
                  'AMERICAN AVOCET',
                  'AMERICAN BITTERN',
                  'AMERICAN COOT',
                  'AMERICAN GOLDFINCH',
                  'AMERICAN KESTREL',
                  'AMERICAN PIPIT',
                  'AMERICAN REDSTART',
                  'ANHINGA',
                  'ANNAS HUMMINGBIRD',
                  'ANTBIRD',
                  'ARARIPE MANAKIN',
                  'ASIAN CRESTED IBIS',
                  'BALD EAGLE',
                  'BALI STARLING',
                  'BALTIMORE ORIOLE',
                  'BANANAQUIT',
                  'BAR-TAILED GODWIT',
                  'BARN OWL',
                  'BARN SWALLOW',
                  'BARRED PUFFBIRD',
                  'BAY-BREASTED WARBLER',
                  'BEARDED BARBET',
                  'BELTED KINGFISHER',
                  'BIRD OF PARADISE',
                  'BLACK FRANCOLIN',
                  'BLACK SKIMMER',
                  'BLACK SWAN',
                  'BLACK THROATED WARBLER',
                  'BLACK VULTURE',
                  'BLACK-CAPPED CHICKADEE',
                  'BLACK-NECKED GREBE',
                  'BLACK-THROATED SPARROW',
                  'BLACKBURNIAM WARBLER',
                  'BLUE GROUSE',
                  'BLUE HERON',
                  'BOBOLINK',
                  'BROWN NOODY',
                  'BROWN THRASHER',
                  'CACTUS WREN',
                  'CALIFORNIA CONDOR',
                  'CALIFORNIA GULL',
                  'CALIFORNIA QUAIL',
                  'CANARY',
                  'CAPE MAY WARBLER',
                  'CAPUCHINBIRD',
                  'CARMINE BEE-EATER',
                  'CASPIAN TERN',
                  'CASSOWARY',
                  'CHARA DE COLLAR',
                  'CHIPPING SPARROW',
                  'CHUKAR PARTRIDGE',
                  'CINNAMON TEAL',
                  'COCK OF THE  ROCK',
                  'COCKATOO',
                  'COMMON GRACKLE',
                  'COMMON HOUSE MARTIN',
                  'COMMON LOON',
                  'COMMON POORWILL',
                  'COMMON STARLING',
                  'COUCHS KINGBIRD',
                  'CRESTED AUKLET',
                  'CRESTED CARACARA',
                  'CROW',
                  'CROWNED PIGEON',
                  'CUBAN TODY',
                  'CURL CRESTED ARACURI',
                  'D-ARNAUDS BARBET',
                  'DARK EYED JUNCO',
                  'DOWNY WOODPECKER',
                  'EASTERN BLUEBIRD',
                  'EASTERN MEADOWLARK',
                  'EASTERN ROSELLA',
                  'EASTERN TOWEE',
                  'ELEGANT TROGON',
                  'ELLIOTS  PHEASANT',
                  'EMPEROR PENGUIN',
                  'EMU',
                  'EURASIAN MAGPIE',
                  'EVENING GROSBEAK',
                  'FLAME TANAGER',
                  'FLAMINGO',
                  'FRIGATE',
                  'GAMBELS QUAIL',
                  'GILA WOODPECKER',
                  'GILDED FLICKER',
                  'GLOSSY IBIS',
                  'GOLD WING WARBLER',
                  'GOLDEN CHEEKED WARBLER',
                  'GOLDEN CHLOROPHONIA',
                  'GOLDEN EAGLE',
                  'GOLDEN PHEASANT',
                  'GOLDEN PIPIT',
                  'GOULDIAN FINCH',
                  'GRAY CATBIRD',
                  'GRAY PARTRIDGE',
                  'GREEN JAY',
                  'GREY PLOVER',
                  'GUINEAFOWL',
                  'GYRFALCON',
                  'HARPY EAGLE',
                  'HAWAIIAN GOOSE',
                  'HOODED MERGANSER',
                  'HOOPOES',
                  'HORNBILL',
                  'HORNED GUAN',
                  'HORNED SUNGEM',
                  'HOUSE FINCH',
                  'HOUSE SPARROW',
                  'IMPERIAL SHAQ',
                  'INCA TERN',
                  'INDIAN BUSTARD',
                  'INDIGO BUNTING',
                  'JABIRU',
                  'JAVAN MAGPIE',
                  'KAKAPO',
                  'KILLDEAR',
                  'KING VULTURE',
                  'KIWI',
                  'KOOKABURRA',
                  'LARK BUNTING',
                  'LEARS MACAW',
                  'LILAC ROLLER',
                  'LONG-EARED OWL',
                  'MALABAR HORNBILL',
                  'MALACHITE KINGFISHER',
                  'MALEO',
                  'MALLARD DUCK',
                  'MANDRIN DUCK',
                  'MARABOU STORK',
                  'MASKED BOOBY',
                  'MIKADO  PHEASANT',
                  'MOURNING DOVE',
                  'MYNA',
                  'NICOBAR PIGEON',
                  'NORTHERN CARDINAL',
                  'NORTHERN FLICKER',
                  'NORTHERN GANNET',
                  'NORTHERN GOSHAWK',
                  'NORTHERN JACANA',
                  'NORTHERN MOCKINGBIRD',
                  'NORTHERN PARULA',
                  'NORTHERN RED BISHOP',
                  'OCELLATED TURKEY',
                  'OKINAWA RAIL',
                  'OSPREY',
                  'OSTRICH',
                  'PAINTED BUNTIG',
                  'PALILA',
                  'PARADISE TANAGER',
                  'PARUS MAJOR',
                  'PEACOCK',
                  'PELICAN',
                  'PEREGRINE FALCON',
                  'PHILIPPINE EAGLE',
                  'PINK ROBIN',
                  'PUFFIN',
                  'PURPLE FINCH',
                  'PURPLE GALLINULE',
                  'PURPLE MARTIN',
                  'PURPLE SWAMPHEN',
                  'QUETZAL',
                  'RAINBOW LORIKEET',
                  'RAZORBILL',
                  'RED FACED CORMORANT',
                  'RED FACED WARBLER',
                  'RED HEADED DUCK',
                  'RED HEADED WOODPECKER',
                  'RED HONEY CREEPER',
                  'RED THROATED BEE EATER',
                  'RED WINGED BLACKBIRD',
                  'RED WISKERED BULBUL',
                  'RING-NECKED PHEASANT',
                  'ROADRUNNER',
                  'ROBIN',
                  'ROCK DOVE',
                  'ROSY FACED LOVEBIRD',
                  'ROUGH LEG BUZZARD',
                  'RUBY THROATED HUMMINGBIRD',
                  'RUFOUS KINGFISHER',
                  'RUFUOS MOTMOT',
                  'SAND MARTIN',
                  'SCARLET IBIS',
                  'SCARLET MACAW',
                  'SHOEBILL',
                  'SMITHS LONGSPUR',
                  'SNOWY EGRET',
                  'SNOWY OWL',
                  'SORA',
                  'SPANGLED COTINGA',
                  'SPLENDID WREN',
                  'SPOON BILED SANDPIPER',
                  'SPOONBILL',
                  'STEAMER DUCK',
                  'STORK BILLED KINGFISHER',
                  'STRAWBERRY FINCH',
                  'STRIPPED SWALLOW',
                  'SUPERB STARLING',
                  'TAIWAN MAGPIE',
                  'TAKAHE',
                  'TASMANIAN HEN',
                  'TEAL DUCK',
                  'TIT MOUSE',
                  'TOUCHAN',
                  'TOWNSENDS WARBLER',
                  'TREE SWALLOW',
                  'TRUMPTER SWAN',
                  'TURKEY VULTURE',
                  'TURQUOISE MOTMOT',
                  'VARIED THRUSH',
                  'VENEZUELIAN TROUPIAL',
                  'VERMILION FLYCATHER',
                  'VIOLET GREEN SWALLOW',
                  'WATTLED CURASSOW',
                  'WHIMBREL',
                  'WHITE CHEEKED TURACO',
                  'WHITE NECKED RAVEN',
                  'WHITE TAILED TROPIC',
                  'WILD TURKEY',
                  'WILSONS BIRD OF PARADISE',
                  'WOOD DUCK',
                  'YELLOW CACIQUE',
                  'YELLOW HEADED BLACKBIRD']

    def bird_classifier(self):
        # load model
        model = load_model('IRv2_model.h5')

        # summarize model
        #model.summary()
        imagename = self.filename
        test_image = image.load_img(imagename, target_size = (224, 224, 3))
        test_image = image.img_to_array(test_image)
        test_image = test_image/255
        test_image = np.expand_dims(test_image, axis = 0)
        prediction = model.predict(test_image)
        score = tf.nn.softmax(prediction[0])
        # op =str("This image most likely belongs to {} with a {:.2f} percent confidence."
        #      .format(birds.birds_list[np.argmax(score)], 100 * np.max(prediction[0])))
        output ="This image most likely belongs " +str(birds.birds_list[np.argmax(score)])+" with "+str(100 * np.max(prediction[0]))+" percent confidence"
        print("prediction completed")

        return [{ "image" : output}]



